services:
  app:
    build:
      context: .
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local